language: node_js
node_js:
  - "11"
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./build
  - git init
  - git config user.name "wuxianqiang"
  - git config user.email "2631640352@qq.com"
  - git add -A
  - git commit -m "init"
  - git push --force "https://${TOKEN}@github.com/wuxianqiang/vue-admin.git" "master:gh-pages"
branches:
  only:
    - master